In [7]:
import copy
import numpy

In [2]:
coeff = numpy.array([[2, 2, 3], [4, 7, 7], [-2, 4, 5]], dtype=float)

In [3]:
L = numpy.zeros(coeff.shape)
U = numpy.zeros(coeff.shape)

# 计算 U1 和 L1

In [4]:
# 计算 U1
row = coeff.shape[0]
col = coeff.shape[1]
U[0] = coeff[0]
print(U)

[[2. 2. 3.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# 计算L1
L[0][0] = 1
for i in range(1, row):
    L[i][0] = coeff[i][0] / U[0][0]
print(L)

[[ 1.  0.  0.]
 [ 2.  0.  0.]
 [-1.  0.  0.]]


# 计算 U2 和 L2

In [14]:
# 计算 U2
k = 1
i = k
U1 = copy.deepcopy(U)
while i < col:
    t_sum = 0
    j = 0
    while j < k:
        t_sum = t_sum + L[k][j] * U[j][i]
        j += 1
    U[k][i] = coeff[k][i] - t_sum
    i += 1
print(U)

[[2. 2. 3.]
 [0. 3. 1.]
 [0. 0. 0.]]


In [18]:
# 计算 L2
i = k
L[i][k] = 1
i += 1
L1 = copy.deepcopy(L)
while i < row:
    t_sum = 0
    j = 0
    while j < k:
        t_sum = t_sum + L[i][j] * U[j][k]
        j += 1
    L[i][k] = (coeff[i][k] - t_sum) / U[k][k]
    i += 1
print(L)

[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  2.  0.]]


# 计算 U3 和 L3

In [19]:
# 计算 U3
k = 2
i = k
U1 = copy.deepcopy(U)
while i < col:
    t_sum = 0
    j = 0
    while j < k:
        t_sum = t_sum + L[k][j] * U[j][i]
        j += 1
    U1[k][i] = coeff[k][i] - t_sum
    i += 1
print(U1)

[[2. 2. 3.]
 [0. 3. 1.]
 [0. 0. 6.]]


In [21]:
# 计算 L3
i = k
L[i][k] = 1
i += 1
L1 = copy.deepcopy(L)
while i < row:
    t_sum = 0
    j = 0
    while j < k:
        t_sum = t_sum + L[i][j] * U[j][k]
        j += 1
    L[i][k] = (coeff[i][k] - t_sum) / U[k][k]
    i += 1
print(L)

[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  2.  1.]]


# 封装为函数

In [31]:
def LUDecompose(A: numpy.ndarray) -> dict:
    """矩阵的 LU 分解，杜利特尔形式
    Args:
        :param A - 待分解的矩阵
    Returns:
        dict - 一个包含分解后L和U阵的字典
    """
    row = A.shape[0]
    col = A.shape[1]
    L = numpy.identity(min(A.shape), dtype=float)
    U = numpy.zeros(A.shape, dtype=float)

    U[0] = A[0]
    for i in range(1, row):
        L[i][0] = A[i][0] / U[0][0]
    
    k = 1
    while k < row:
        # 计算U
        i = k
        while i < col:
            t_sum = 0
            j = 0
            while j < k:
                t_sum = t_sum + L[k][j] * U[j][i]
                j += 1
            U[k][i] = A[k][i] - t_sum
            i += 1
        # 计算L
        i = k + 1
        while i < row:
            t_sum = 0
            j = 0
            while j < k:
                t_sum = t_sum + L[i][j] * U[j][k]
                j += 1
            L[i][k] = (A[i][k] - t_sum) / U[k][k]
            i += 1
        k += 1
    
    return {"L": L, "U":U}

In [32]:
t1 = LUDecompose(numpy.array([[2, 2, 3], [4, 7, 7], [-2, 4, 5]], dtype=float))
print(t1["L"])
print(t1["U"])

[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  2.  1.]]
[[2. 2. 3.]
 [0. 3. 1.]
 [0. 0. 6.]]


In [33]:
t2 = LUDecompose(numpy.array([[2, 1, 2], [4, 3, 1], [6, 1, 5]], dtype=float))
print(t2["L"])
print(t2["U"])

[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [ 3. -2.  1.]]
[[ 2.  1.  2.]
 [ 0.  1. -3.]
 [ 0.  0. -7.]]


In [34]:
t3 = LUDecompose(numpy.array([[2, 2, 3, 4], [2, 4, 9, 16], [4, 8, 24, 64], [6, 16, 51, 100]], dtype=float))
print(t3["L"])
print(t3["U"])

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [2. 2. 1. 0.]
 [3. 5. 2. 1.]]
[[  2.   2.   3.   4.]
 [  0.   2.   6.  12.]
 [  0.   0.   6.  32.]
 [  0.   0.   0. -36.]]


In [62]:
t4 = LUDecompose(numpy.array([[2, 2, 3, 4, 1], [2, 4, 9, 16, 1], [4, 8, 24, 63, 3], [6, 16, 51, 100, -29]], dtype=float))
print(t4["L"])
print(t4["U"])

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [2. 2. 1. 0.]
 [3. 5. 2. 1.]]
[[  2.   2.   3.   4.   1.]
 [  0.   2.   6.  12.   0.]
 [  0.   0.   6.  31.   1.]
 [  0.   0.   0. -34. -34.]]


In [60]:
c = t4["U"].T[0:4][:].T
b = t4["U"].T[4].reshape((4, 1))
n = c.shape[0] - 1
row = c.shape[0]
col = c.shape[1]
b[n] = b[n] / c[n][n]
n -= 1
while n >= 0:
    t_sum = 0
    i = n
    j = i + 1
    while j < col:
        t_sum += c[i][j] * b[j]
        j += 1
    b[n] = (b[n] - t_sum) / c[n][n]
    n -= 1
print(b)

[[-7.13970588]
 [ 6.72058824]
 [-0.68137255]
 [-0.02941176]]


# 将高斯消元法的回代过程封装为函数

In [63]:
def gauss_back(c: numpy.ndarray, b: numpy.ndarray) -> numpy.ndarray:
    """高斯消元法的回代过程
    Args:
        :param - c：系数矩阵
        :param - b：常数矩阵
    Returns:
        numpy.ndarray - 计算结果
    """
    # 深拷贝，避免对形参的影响
    c1 = copy.deepcopy(c)
    b1 = copy.deepcopy(b)

    col = c1.shape[1]
    n = c1.shape[0] - 1
    b1[n] = b1[n] / c1[n][n]
    n -= 1
    while n >= 0:
        t_sum = 0
        i = n
        j = i + 1
        while j < col:
            t_sum += c1[i][j] * b1[j]
            j += 1
        b1[n] = (b1[n] - t_sum) / c1[n][n]
        n -= 1
    return b1

In [66]:
t5 = copy.deepcopy(t4)
print(t5["U"].T[0:4][:].T)
print(t5["U"].T[4].reshape((4, 1)))
print(gauss_back(t5["U"].T[0:4][:].T, t5["U"].T[4].reshape((4, 1))))

[[  2.   2.   3.   4.]
 [  0.   2.   6.  12.]
 [  0.   0.   6.  31.]
 [  0.   0.   0. -34.]]
[[  1.]
 [  0.]
 [  1.]
 [-34.]]
[[-3.]
 [ 9.]
 [-5.]
 [ 1.]]


In [69]:
t6 = LUDecompose(numpy.array([[1, 1, -1, 1], [1, 2, -2, 0], [-2, 1, 1, 0]], dtype=float))
print(t6["U"].T[0:3][:].T)
print(t6["U"].T[3].reshape((3, 1)))
print(gauss_back(t6["U"].T[0:3][:].T, t6["U"].T[3].reshape((3, 1))))

[[ 1.  1. -1.]
 [ 0.  1. -1.]
 [ 0.  0.  2.]]
[[ 1.]
 [-1.]
 [ 5.]]
[[2. ]
 [1.5]
 [2.5]]


In [71]:
t7 = LUDecompose(numpy.array([[1, 1, -1, 0], [1, 2, -2, 1], [-2, 1, 1, 0]], dtype=float))
print(t7["U"].T[0:3][:].T)
print(t7["U"].T[3].reshape((3, 1)))
print(gauss_back(t7["U"].T[0:3][:].T, t7["U"].T[3].reshape((3, 1))))

[[ 1.  1. -1.]
 [ 0.  1. -1.]
 [ 0.  0.  2.]]
[[ 0.]
 [ 1.]
 [-3.]]
[[-1. ]
 [-0.5]
 [-1.5]]


In [72]:
t8 = LUDecompose(numpy.array([[1, 1, -1, 0], [1, 2, -2, 0], [-2, 1, 1, 1]], dtype=float))
print(t8["U"].T[0:3][:].T)
print(t8["U"].T[3].reshape((3, 1)))
print(gauss_back(t8["U"].T[0:3][:].T, t8["U"].T[3].reshape((3, 1))))

[[ 1.  1. -1.]
 [ 0.  1. -1.]
 [ 0.  0.  2.]]
[[0.]
 [0.]
 [1.]]
[[0. ]
 [0.5]
 [0.5]]
