In [1]:
import copy
import numpy

In [2]:
# coeff = numpy.array([[2, 1, 1], [1, 3, 2], [1, 2, 2]], dtype=float)
# b = numpy.array([[4], [6], [5]], dtype=float)
coeff = numpy.array([[4, 3, 1], [2, 1, 2], [6, 1, 5]], dtype=float)
b = numpy.array([[11], [6], [13]], dtype=float)

In [3]:
print(coeff.shape)
print(b.shape)

(3, 3)
(3, 1)


# 高斯消去法

In [4]:
# 消元
c = copy.deepcopy(coeff)
b1 = copy.deepcopy(b)
row = c.shape[0]
col = c.shape[1]
for k in range(row):
    i = k + 1
    while i < row:
        m = c[i][k] / c[k][k]
        c[i] = (-m * c[k]) + c[i]
        b1[i] = (-m * b1[k]) + b1[i]
        i += 1
print(c)
print(b1)

[[ 4.   3.   1. ]
 [ 0.  -0.5  1.5]
 [ 0.   0.  -7. ]]
[[11. ]
 [ 0.5]
 [-7. ]]


In [5]:
# 回代
n = c.shape[0] - 1
row = c.shape[0]
col = c.shape[1]
b2 = copy.deepcopy(b1)
b2[n] = b2[n] / c[n][n]
n -= 1
while n >= 0:
    tsum = 0
    i = n
    j = i + 1
    while j < col:
        tsum += c[i][j] * b2[j]
        j += 1
    b2[n] = (b2[n] - tsum) / c[n][n]
    n -= 1
print(b2)

[[1.]
 [2.]
 [1.]]


# 列选主元高斯消去法

In [10]:
coeff1 = numpy.array([[0, 1, 1], [1, 3, 2], [1, 2, 2]], dtype=float)
b3 = numpy.array([[4], [6], [5]], dtype=float)
row = coeff1.shape[0]
col = coeff1.shape[1]
for k in range(row):
    # 对列选主元
    ck = coeff1.T[k][k:col]
    t = numpy.where(ck == max(ck))
    t_max = ck[t[0][0]]
    if t_max == 0:
        print("矩阵奇异")
        break
    t1 = numpy.copy(coeff1[k+t[0][0]])
    coeff1[k+t[0][0]] = coeff1[k]
    coeff1[k] = t1
    # 修改b矩阵
    t2 = numpy.copy(b3[k+t[0][0]])
    b3[k+t[0][0]] = b3[k]
    b3[k] = t2

    # 转入一般的高斯消元法
    i = k + 1
    while i < row:
        m = coeff1[i][k] / coeff1[k][k]
        coeff1[i] = (-m * coeff1[k]) + coeff1[i]
        b3[i] = (-m * b3[k]) + b3[i]
        i += 1
print(coeff1)
print(b3)

[[1. 3. 2.]
 [0. 1. 1.]
 [0. 0. 1.]]
[[6.]
 [4.]
 [3.]]


In [11]:
#  回代
n = coeff1.shape[0] - 1
row = coeff1.shape[0]
col = coeff1.shape[1]
b4 = copy.deepcopy(b3)
b4[n] = b4[n] / coeff1[n][n]
n -= 1
while n >= 0:
    tsum = 0
    i = n
    j = i + 1
    while j < col:
        tsum += coeff1[i][j] * b4[j]
        j += 1
    b4[n] = (b4[n] - tsum) / coeff1[n][n]
    n -= 1
print(b4)

[[-3.]
 [ 1.]
 [ 3.]]


# 高斯-约当消去法

In [7]:
coeff2 = numpy.array([[4, 3, 1], [2, 1, 2], [6, 1, 5]], dtype=float)
b5 = numpy.array([[11], [6], [13]], dtype=float)
row = coeff2.shape[0]
col = coeff2.shape[1]
# 消元
for k in range(row):
    i = 0
    for i in range(row):
        if i == k:
            continue
        m = coeff2[i][k] / coeff2[k][k]
        coeff2[i] = (-m * coeff2[k]) + coeff2[i]
        b5[i] = (-m * b5[k]) + b5[i]
print(coeff2)
print(b5)

[[ 4.   0.   0. ]
 [ 0.  -0.5  0. ]
 [ 0.   0.  -7. ]]
[[ 4.]
 [-1.]
 [-7.]]


In [8]:
# 求解
for k in range(row):
    b5[k] = b5[k] / coeff2[k][k]
print(b5)

[[1.]
 [2.]
 [1.]]


# 归一化的高斯-约当法求逆矩阵

In [12]:
A = numpy.array([[1, 1, -1], [2, 1, 0], [1, -1, 0]], dtype=float)
A1 = numpy.concatenate((A, numpy.identity(A.shape[0], dtype=float)), axis=1)
row = A1.shape[0]
col = A1.shape[1]
for k in range(row):
    # 选主元
    ck = A1.T[k][k:row]
    ck = abs(ck)
    t = numpy.where(ck == max(ck))
    t_max = ck[t[0][0]]
    if t_max == 0:
        print("矩阵奇异")
        break
    t1 = numpy.copy(A1[k+t[0][0]])
    A1[k+t[0][0]] = A1[k]
    A1[k] = t1
    # 归一化
    A1[k] = A1[k] / A1[k][k]
    # 转入一般的高斯-约当消去法
    i = 0
    for i in range(row):
        if i == k:
            continue
        m = A1[i][k] / A1[k][k]
        A1[i] = (-m * A1[k]) + A1[i]
print(numpy.split(A1, 2, axis=1)[1])

[[ 0.          0.33333333  0.33333333]
 [-0.          0.33333333 -0.66666667]
 [-1.          0.66666667 -0.33333333]]


In [13]:
# 用库计算逆矩阵
print(numpy.linalg.inv(A))
print(numpy.matrix(A).I)

[[ 0.          0.33333333  0.33333333]
 [-0.          0.33333333 -0.66666667]
 [-1.          0.66666667 -0.33333333]]
[[ 0.          0.33333333  0.33333333]
 [-0.          0.33333333 -0.66666667]
 [-1.          0.66666667 -0.33333333]]
